"""brevet.wrap: the whole product in one call.

    import brevet

    agent = brevet.wrap(anything)                # zero config
    r = agent.run("triage DEV-4021", task_family="deviation_triage")
    agent.record_final(r.task_id, edited_text, participant="human:me@org")

    agent.dream()                                # mine candidates + compile evals
    agent.dawn()                                 # -> pending candidates
    agent.dawn(decide=(cap_id, "promote"), approver="human:me@org")
    agent.release(to_version="0.2.0", channel="trial", approver="human:me@org",
                  delta_in=0.2, delta_out=0.1)
    agent.recall(cap_id, reason="...", issued_by="human:me@org")
    agent.verify()

`wrap()` auto-detects the framework (LangGraph, Claude Agent SDK, DeepAgents,
AutoGen, LlamaIndex, Pydantic AI, Google ADK, CrewAI, OpenAI Agents, or any
callable), auto-creates a signature-conformant manifest when none exists, and
persists everything under `.brevet/`. Every feature is reachable from the
returned object; the CLI and MCP server are the same functions.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

from brevet.adapters import BaseAdapter, detect, get_adapter
from brevet.assist import ModelAssist, NoModelAssist
from brevet.canonical import Signer
from brevet.chap_bridge import dispatcher_from_ref
from brevet.delta import load_overrides, mine
from brevet.evals import compile_suite
from brevet.evidence import harvest_override
from brevet.ledger import Ledger
from brevet.lifecycle import (
    CapabilityStore,
    dawn_decide,
    recall as _recall,
    release as _release,
)
from brevet.models import (
    AgentManifest,
    AuthorityLayer,
    CapabilityObject,
    OverrideRecord,
    RecallNotice,
    ReleaseChannel,
    ReleaseRecord,
)


@dataclass
class RunResult:
    task_id: str
    output: str
    trace: list[dict[str, Any]] = field(default_factory=list)
    artefact_ref: str = ""


def _default_manifest(name: str) -> AgentManifest:
    return AgentManifest(
        agent=name,
        description=f"Auto-generated by brevet.wrap for '{name}'. Edit agent.yaml to refine.",
        identity_policy={"agent_id": name, "owner": "human:unset@local",
                         "mission_group": None, "may": [], "may_not": []},
        prompt_architecture={},
        cognitive_core={"model_policy": {"local_default": "ollama:gemma4:12b",
                                         "allowed_remote": []}},
        bindings={"tools": {"read": [], "suggest": [], "act": [], "controlled_act": []},
                  "capabilities_lock": "capabilities.lock"},
        runtime_safety={"loop": {"policy": "react", "max_iterations": 8},
                        "evidence": {"ledger": "file:./ledger.jsonl",
                                     "profiles": ["core/1.0", "review/1.0", "brevet/1.0"],
                                     "capture_overrides": True},
                        "evals": {"regression_suite": None, "gate": "conservative",
                                  "repeats": 3},
                        "dream": {"enabled": True,
                                  "consent_scope": "consented_sources_only"}},
    )


def _slug(target: Any) -> str:
    raw = getattr(target, "__name__", None) or type(target).__name__
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", raw).lower()
    return re.sub(r"[^a-z0-9_]", "_", s).strip("_") or "wrapped_agent"


class BrevetAgent:
    """A wrapped agent: your framework underneath, governance around it."""

    def __init__(self, adapter: BaseAdapter, manifest: AgentManifest, workdir: Path,
                 manifest_path: Optional[Path] = None,
                 assist: Optional[ModelAssist] = None):
        self.adapter = adapter
        self.manifest = manifest
        self.workdir = Path(workdir)
        self.workdir.mkdir(parents=True, exist_ok=True)
        self.manifest_path = manifest_path
        self.assist = assist or NoModelAssist()

        ledger_ref = (manifest.runtime_safety.get("evidence", {})
                      .get("ledger", "file:./ledger.jsonl"))
        path = self.workdir / (ledger_ref[5:] if ledger_ref.startswith("file:")
                               else "ledger.jsonl")
        self.ledger = Ledger(path, dispatcher=dispatcher_from_ref(ledger_ref, self.workdir))
        self.store = CapabilityStore(self.workdir / "capabilities.jsonl")
        self.signer = Signer(self.workdir / "keys" / "brevet_ed25519.pem")
        self._drafts: dict[str, str] = {}
        self._families: dict[str, str] = {}

    # ------------------------------------------------------------ waking

    def run(self, task: str, *, task_family: Optional[str] = None,
            context: Optional[dict[str, Any]] = None) -> RunResult:
        task_id = self.ledger.append("brevet.task", {
            "task": task, "task_family": task_family,
            "agent": self.manifest.agent, "agent_version": self.manifest.version,
            "channel": self.manifest.release.get("channel", "shadow"),
        })
        ctx = {"task_id": task_id, **(context or {})}
        output, trace = self.adapter.invoke(task, ctx)
        artefact_ref = self.ledger.append("brevet.artefact", {
            "task_id": task_id, "output": output,
            "trace_len": len(trace), "trace": trace[-50:],
        }, refs=[task_id])
        self._drafts[task_id] = output
        self._families[task_id] = task_family or "default"
        return RunResult(task_id, output, trace, artefact_ref)

    def record_final(self, task_id: str, final: str, *,
                     participant: str = "human:unknown", rationale: str = "",
                     tags: Optional[list[str]] = None) -> Optional[OverrideRecord]:
        override = harvest_override(
            task_id=task_id, draft=self._drafts.get(task_id, ""), final=final,
            participant=participant, rationale=rationale, tags=tags or [],
            task_family=self._families.get(task_id, "default"),
        )
        if override is None:
            self.ledger.append("brevet.artefact",
                               {"task_id": task_id, "accepted_verbatim": True}, refs=[task_id])
            return None
        self.ledger.append("brevet.override", override.model_dump(), refs=[task_id])
        return override

    # ---------------------------------------------------------- sleeping

    def dream(self) -> dict[str, int]:
        """Offline cycle: mine ``enacted ⊖ specified`` into Evidence-layer
        candidates and compile the override-derived regression suite."""
        overrides = load_overrides(self.ledger)
        model_family = (self.manifest.cognitive_core.get("model_policy", {})
                        .get("local_default", "").split(":")[1:2] or [None])[0]
        candidates = mine(overrides, model_family=model_family,
                          assist=self.assist, ledger=self.ledger)
        for cand in candidates:
            self.store.add(cand)
            self.ledger.append("brevet.candidate",
                               {"capability_id": cand.capability_id, "title": cand.title,
                                "recurrence": cand.evidence.recurrence_count},
                               refs=[cand.capability_id])
        cases = compile_suite([o for o in overrides if not o.intent_preserved])
        for case in cases:
            self.store.add(case)
        return {"overrides": len(overrides), "candidates": len(candidates),
                "eval_cases": len(cases)}

    # -------------------------------------------------------------- dawn

    def dawn(self, *, decide: Optional[tuple[str, str]] = None,
             approver: Optional[str] = None,
             to_layer: AuthorityLayer | str = AuthorityLayer.advisory,
             notes: str = "") -> list[CapabilityObject] | CapabilityObject:
        """No arguments: the pending queue. With ``decide=(cap_id, outcome)``
        and ``approver=``: apply one human decision."""
        if decide is None:
            return self.store.pending()
        if approver is None:
            raise PermissionError("dawn decisions require approver=<human|mission_group id>")
        cap_id, outcome = decide
        return dawn_decide(self.store, self.ledger, cap_id, outcome,
                           approver=approver, to_layer=AuthorityLayer(to_layer), notes=notes)

    # ----------------------------------------------------------- release

    def evaluate(self, *, scorer: Any = None) -> dict[str, Any]:
        """Execute the compiled regression suite against the current agent."""
        from brevet.runner import EvalRunner
        return EvalRunner(self, scorer=scorer).run()

    def release(self, *, to_version: str, channel: str = "shadow",
                approver: str, delta_in: float = 0.0, delta_out: float = 0.0,
                rationale: str = "") -> ReleaseRecord:
        self.manifest, lock, record = _release(
            self.manifest, self.store, self.ledger, self.signer,
            to_version=to_version, channel=ReleaseChannel(channel), approver=approver,
            eval_summary={"delta_held_in": delta_in, "delta_held_out": delta_out,
                          "gate": "conservative"},
            rationale=rationale,
        )
        if self.manifest_path:
            self.manifest_path.write_text(yaml.safe_dump(
                self.manifest.model_dump(exclude_none=False), sort_keys=False))
            (self.manifest_path.parent / "capabilities.lock").write_text(
                lock.model_dump_json(indent=2))
        return record

    def recall(self, capability_id: str, *, reason: str, issued_by: str,
               reason_class: str = "incorrect", severity: str = "high",
               action: str = "rollback") -> RecallNotice:
        releases = [ReleaseRecord(**e["body"]) for e in self.ledger.read("brevet.release")]
        return _recall(self.store, self.ledger, capability_id, reason=reason,
                       reason_class=reason_class, severity=severity,
                       issued_by=issued_by, releases=releases, action=action)

    # ------------------------------------------------------------- audit

    def verify(self) -> tuple[bool, int]:
        return self.ledger.verify()

    def status(self) -> dict[str, Any]:
        caps = self.store.all().values()
        by_layer: dict[str, int] = {}
        revoked = 0
        for c in caps:
            if c.revocation_status.value == "active":
                by_layer[c.authority_layer.value] = by_layer.get(c.authority_layer.value, 0) + 1
            else:
                revoked += 1
        ok, n = self.ledger.verify()
        return {
            "agent": self.manifest.agent,
            "version": self.manifest.version,
            "channel": self.manifest.release.get("channel", "shadow"),
            "adapter": self.adapter.name,
            "signed": bool(self.manifest.signature),
            "capabilities": by_layer,
            "revoked": revoked,
            "pending_dawn": len(self.store.pending()),
            "envelopes": n,
            "chain_ok": ok,
        }


# Backwards-compatible alias (v0.0.1 name).
BrevetShell = BrevetAgent


def wrap(target: Any, *, manifest: str | Path | AgentManifest | None = None,
         adapter: Optional[str] = None, workdir: str | Path = ".brevet",
         assist: Optional[ModelAssist] = None) -> BrevetAgent:
    """Wrap any agent. Zero config required: if no manifest exists, a
    signature-conformant one is generated and persisted to <workdir>/agent.yaml."""
    workdir = Path(workdir)
    manifest_path: Optional[Path] = None

    if isinstance(manifest, AgentManifest):
        m = manifest
    else:
        manifest_path = Path(manifest) if manifest else workdir / "agent.yaml"
        if manifest_path.exists():
            m = AgentManifest(**yaml.safe_load(manifest_path.read_text()))
        else:
            m = _default_manifest(_slug(target))
            manifest_path.parent.mkdir(parents=True, exist_ok=True)
            manifest_path.write_text(yaml.safe_dump(
                m.model_dump(exclude_none=False), sort_keys=False))

    adapter_name = adapter or detect(target)
    return BrevetAgent(get_adapter(adapter_name)(target), m, workdir,
                       manifest_path=manifest_path, assist=assist)
